# Generated by Django 4.1 on 2022-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("pwd", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=128, unique=True)),
                ("nickName", models.CharField(max_length=30, unique=True)),
                ("registerDttm", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
