# Generated by Django 4.1 on 2022-08-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="nickName", new_name="nickname",
        ),
    ]
