# Generated by Django 4.1 on 2022-08-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("reviews", "0002_rename_nickname_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("bno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("contents", models.TextField(verbose_name="내용")),
                ("category", models.CharField(db_index=True, max_length=32)),
                ("write_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now_add=True)),
                ("hits", models.PositiveIntegerField(default=0)),
                ("meta_json", models.TextField()),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="User",),
    ]
