# Generated by Django 4.1 on 2022-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="contents",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
