# Generated by Django 4.1 on 2022-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_schedule_contents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="contents",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
